config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'
  
  get 'all_users' => 'epicenter#all_users'

  get 'following' => 'epicenter#following'
  get 'followers' => 'epicenter#followers'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'tag_tweet' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tweet_tags
  has_many :tags, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
before_validation :link_check, on: :create

belongs_to :user

has_many :tweet_tags
has_many :tags, through: :tweet_tags

validates :message, presence: true, length: {maximum: 110, too_long: "You have hit your word cap!"}

after_validation :apply_link, on: :create

private

def apply_link
  arr = self.message.split
  index = arr.map { |x| x.include?("http://") || x.include?("https://") }.index(true)

  if index
    url = arr[index]
    arr[index] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
  end

self.message = arr.join(" ")
end

def link_check
  if self.message.include? "http://"
    check = true
  elsif self.message.include? "https://"
    check = true
  else
    check = false
  end

  if check == true
    arr = self.message.split
    index = arr.map{ |x| x.include? "http"}.index(true)
    self.link = arr[index]
    if arr[index].length > 23
      arr[index] = "#{arr[index][0..20]}..."
    end
    self.message = arr.join(" ")

  end
  end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :user_id


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :tweets, dependent: :destroy
serialize :following, Array
validates :username, presence: true, uniqueness: true
mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :bio, :location, :avatar, :following])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :bio, :location, :avatar, :following])
  end

end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  before_action :set_user, only: [:followers, :following]


  def following
    @users = []

    User.all.each do |user|
      if @user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def followers
    @users = []

    User.all.each do |user|
      if user.following.include?(user.id)
        @users.push(user)
      end
    end
  end

  def all_users
    @users = User.order(:username)
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def feed
    @tweet = Tweet.new

      @following_tweets = []

      Tweet.all.each do |tweet|
        if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user.id
        @following_tweets.push(tweet)
        end
      end
    end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    current_user.following.push(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save

    redirect_to show_user_path(id: params[:id])
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save

        @tweet = get_tagged(@tweet)
        @tweet.save

        message_arr = @tweet.message.split

        message_arr = @tweet.message.split

        message_arr.each_with_index do |word, index|
          if word[0] == "#"
            if Tag.pluck(:phrase).include?(word)
              #save that Tag as a variable (to use in TweetTag creation)
              tag = Tag.find_by(phrase: word)
            else
            #creates a new instance of a Tag
              tag = Tag.create(phrase: word)
            end
            tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)
            message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
          end
        end

        @tweet.update(message: message_arr.join(" "))

        format.html { redirect_to root_url, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def get_tagged(tweet)
          message_arr = tweet.message.split
          message_arr.each_with_index do |word, index|
            if word[0] == "#"
              if Tag.pluck(:phrase).include?(word)
                tag = Tag.find_by(phrase: word)
              else
                tag = Tag.create(phrase: word)
              end
              tweet_tag = TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
              message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
            end
          end

          tweet.message = message_arr.join(" ")
            return tweet
        end
end

app/views/epicenter/_user_list.html.erb
<div class="row">
  <% @users.each_with_index do |user, index| %>

  <div class="col-md-3">
    <div class="well user-list-wells">
      <div class="row">
        <% unless user.avatar.blank? %>
        <%= image_tag user.avatar.url, size: 100 %>
        <% end %>
      </div>
      <div class="col-md-6">
        <p>
          <% if current_user.following.include?(user.id) %>
            <%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary",
              id: "unfollow_btn_#{index}" %>
          <% else %>
            <% if current_user.id != user.id %>
              <%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
<div class="row">
  <%= link_to show_user_path(id: user.id) do %>
    <h3><%= user.name %></h3>
    <p><%= "@#{user.username}" %> </p>
<% end %>
    <p class="bio">
      <%= user.bio %>
    </p>
</div>
</div>
</div>

<script>
  $(document).ready(function() {
    $('#unfollow_btn_<%= index %>').hover(function(){
      $(this).removeClass('btn-primary');
      $(this).addClass('btn-default');
      $(this).html("Unfollow");
    }, function(){
      $(this).html("Following");
      $(this).removeClass('btn-danger');
      $(this).addClass('btn-primary');
    });
  });
</script>
<% end %>

</div>

app/views/epicenter/all_users.html.erb
<h1>All Twitter Users</h1>

<%= render 'user_list' %>

app/views/epicenter/feed.html.erb
<h1><%= current_user.username %> </h1>
<%= render 'tweets/form', tweet: @tweet %>
<h3>Here is what your friends are saying:</h3>

<% @following_tweets.reverse_each do |tweet| %>
<div class="well">
  <p>
    <%= image_tag tweet.user.avatar.url, size: 25 %>
    <%= tweet.user.name %>
    <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
    <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
    <%= tweet.created_at.strftime ('%b %e') if Time.now - tweet.created_at > 86400 %>
  </p>
  <p><%= tweet.message.html_safe %></p>
</div>
<% end %>

app/views/epicenter/followers.html.erb
<h2><%= @user.name %>'s Followers</h2>

<%= render 'user_list' %>

app/views/epicenter/following.html.erb
<h2><%= @user.name %> is following: </h2>

<%= render 'user_list' %>

app/views/epicenter/show_user.html.erb
<%= image_tag @user.avatar.url size: 25 %>

<h4><%= @user.name %> </h4>
<h4><%= @user.location %> </h4>
<h5><%= @user.bio %></h5>

<%= link_to "Followers", followers_path(id: @user.id), class: "btn btn-default" %> |
<%= link_to "Following", following_path(id: @user.id), class: "btn btn-default" %>

<p>
  <% if current_user.following.include?(@user.id) %>
    <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
  <% else %>
    <% if current_user.id != @user.id %>
    <%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
  <% end %>
  <% end %>
</p>

<% @user.tweets.order(created_at: :desc).each do |tweet| %>
<div class="well">
  <p>
    <%= image_tag tweet.user.avatar.url, size: 25 %>
    <%= tweet.user.name %>
    @<%= tweet.user.username %>
    <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
    <%= tweet.created_at.strftime ('%b %e') if Time.now - tweet.created_at > 86400 %>
  </p>
  <p><%= tweet.message.html_safe %></p>
</div>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<div>
  <h1><%= @tag.phrase %></h1>
</div>

<div class="row">
  <!-- a place for current user stats -->
  <div>
    <% @tag.tweets.order(created_at: :desc).each do |tweet| %>
      <div class="well">
        <p>
          <%= image_tag tweet.user.avatar.url, size: 25 %>
          <%= tweet.user.name %>
          <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
          <%= time_ago_in_words(tweet.created_at) if Time.now - tweet.created_at < 86400 %>
          <%= tweet.created_at.strftime ('%b %e') if Time.now - tweet.created_at > 86400 %>
        </p>
        <p>
          <%= tweet.messge.html_safe %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "New Tweet", new_tweet_path %></li>
      <li><%= link_to "All Users", all_users_path %> </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class= "dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <% if current_user.avatar.blank? == false %>
                        <%= image_tag current_user.avatar.url, size:25 %>
                    <% end %>
                  @<%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
           </ul>
           </li>
        <% end %>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterNinjaPanda</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :message, placeholder: "Speak your mind!", class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit "Tweet", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Tweets</h1>

<table class="table"
  <thead>
    <tr>
      <th>Message</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id)%></td>
        <td><%= tweet.created_at %></td>
        <td><%= link_to 'Show', tweet, class: "btn btn-info btn-sm"%></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-success" %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h3> <%= @tweet.user.username %> 's Tweet</h3>

<div class="well">
  <p>
    <%= image_tag @tweet.user.avatar.url, size: 25 %>
    <%= @tweet.user.name %>
    <%= link_to "@#{@tweet.user.username}", show_user_path(id: @tweet.user.id) %>
    🕐 <%= time_ago_in_words(@tweet.created_at) %>
  </p>
  <p><%= @tweet.message.html_safe %> </p>
</div>



<%= link_to 'Edit', edit_tweet_path(@tweet), class: "btn btn-warning" %> |
<%= link_to 'Back', tweets_path, class: "btn btn-default" %>